// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC_CGsj621E4n8SXbB5Was68LTtwIgimk',
    appId: '1:22608986937:web:6da75e1f01f0eed3311ee8',
    messagingSenderId: '22608986937',
    projectId: 'social-app-32fe7',
    authDomain: 'social-app-32fe7.firebaseapp.com',
    storageBucket: 'social-app-32fe7.appspot.com',
    measurementId: 'G-JSRL56X7F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuVcs5RwdlyZrQ_zB6N6rtgc0vZTbCR8k',
    appId: '1:22608986937:android:85af788c03214333311ee8',
    messagingSenderId: '22608986937',
    projectId: 'social-app-32fe7',
    storageBucket: 'social-app-32fe7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPZdIXKqqq2bIPyTVHEdrKsOwPEtzd38o',
    appId: '1:22608986937:ios:89ef21ee4424031c311ee8',
    messagingSenderId: '22608986937',
    projectId: 'social-app-32fe7',
    storageBucket: 'social-app-32fe7.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPZdIXKqqq2bIPyTVHEdrKsOwPEtzd38o',
    appId: '1:22608986937:ios:89ef21ee4424031c311ee8',
    messagingSenderId: '22608986937',
    projectId: 'social-app-32fe7',
    storageBucket: 'social-app-32fe7.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC_CGsj621E4n8SXbB5Was68LTtwIgimk',
    appId: '1:22608986937:web:f9ad5d6ac37f34be311ee8',
    messagingSenderId: '22608986937',
    projectId: 'social-app-32fe7',
    authDomain: 'social-app-32fe7.firebaseapp.com',
    storageBucket: 'social-app-32fe7.appspot.com',
    measurementId: 'G-TW9LHRW4WN',
  );
}
